version = 1
enableSodiumMenu = false
itemFrameLODRange = 16
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 3
includeMangroveRoots = true
entityModelCulling = true
endGatewayCulling = true
