name: Push Commit

on:
  push:

jobs:
  upload-packs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Get short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Mrpack fabric/1.21.4
        uses: vimtor/action-zip@v1.2
        with:
          files: modrinth/fabric/1.21.4
          dest: OptimumFuse ${{ env.COMMIT_SHORT_SHA }}+fabric.1.21.4.mrpack

      - name: Upload Mrpacks to Github
        uses: actions/upload-artifact@v4
        with:
          name: Modrinth Releases
          path: ${{ github.workspace }}/*.mrpack

  modrinth-desc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: funnyboy-roks/modrinth-auto-desc@v1.6
        with:
          auth-token: ${{ secrets.MODRINTH_TOKEN }}
          slug: 'optimum-fuse'
