name: Push Commit

on:
  push:

jobs:
  upload-packs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Get short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Mrpack neo/1.21
        uses: vimtor/action-zip@v1.2
        with:
          files: modrinth/neo/1.21
          dest: OptimumFuse ${{ env.COMMIT_SHORT_SHA }}+neo.1.21.mrpack

      - name: Mrpack neo/1.21.1
        uses: vimtor/action-zip@v1.2
        with:
          files: modrinth/neo/1.21.1
          dest: OptimumFuse ${{ env.COMMIT_SHORT_SHA }}+neo.1.21.1.mrpack

      - name: Mrpack fabric/1.21
        uses: vimtor/action-zip@v1.2
        with:
          files: modrinth/fabric/1.21
          dest: OptimumFuse ${{ env.COMMIT_SHORT_SHA }}+fabric.1.21.mrpack

      - name: Mrpack fabric/1.21.1
        uses: vimtor/action-zip@v1.2
        with:
          files: modrinth/fabric/1.21.1
          dest: OptimumFuse ${{ env.COMMIT_SHORT_SHA }}+fabric.1.21.1.mrpack

      - name: Mrpack fabric/1.21.3
        uses: vimtor/action-zip@v1.2
        with:
          files: modrinth/fabric/1.21.3
          dest: OptimumFuse ${{ env.COMMIT_SHORT_SHA }}+fabric.1.21.3.mrpack

      - name: Zip neo/1.21
        uses: vimtor/action-zip@v1.2
        with:
          files: curseforge/neo/1.21
          dest: OptimumFuse ${{ env.COMMIT_SHORT_SHA }}+neo.1.21.zip

      - name: Zip fabric/1.21
        uses: vimtor/action-zip@v1.2
        with:
          files: curseforge/fabric/1.21
          dest: OptimumFuse ${{ env.COMMIT_SHORT_SHA }}+fabric.1.21.zip

      - name: Zip fabric/1.21.1
        uses: vimtor/action-zip@v1.2
        with:
          files: curseforge/fabric/1.21.1
          dest: OptimumFuse ${{ env.COMMIT_SHORT_SHA }}+fabric.1.21.1.zip

      - name: Upload Mrpacks to Github
        uses: actions/upload-artifact@v4
        with:
          name: Modrinth Releases
          path: ${{ github.workspace }}/*.mrpack

      - name: Upload Zips to Github
        uses: actions/upload-artifact@v4
        with:
          name: Curseforge Releases
          path: ${{ github.workspace }}/*.zip

  modrinth-desc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: funnyboy-roks/modrinth-auto-desc@v1.6
        with:
          auth-token: ${{ secrets.MODRINTH_TOKEN }}
          slug: 'optimum-fuse'
